### 
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@trade.com",
  "password": "supersecret"
}

### 
POST http://localhost:8080/auth/create-admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoibW9kZXJhdG9yQHRyYWRlLmNvbSIsInJvbGUiOiJtb2RlcmF0b3IiLCJpYXQiOjE3NjM1NDg0ODgsImV4cCI6MTc2MzYzNDg4OH0.-a9W1vYYzzbxfsqz6dzF9nn_7QG_eRe0EcWyItB-vvE

{
  "name": "Marija Admin",
  "email": "marija.admin@example.com",
  "password": "supersecret",
  "phone": "070123457",
  "role": "admin"
}

### 

POST http://localhost:8080/auth/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoibW9kZXJhdG9yQHRyYWRlLmNvbSIsInJvbGUiOiJtb2RlcmF0b3IiLCJpYXQiOjE3NjM1NDg0ODgsImV4cCI6MTc2MzYzNDg4OH0.-a9W1vYYzzbxfsqz6dzF9nn_7QG_eRe0EcWyItB-vvE

{
  "name": "Nikola User",
  "email": "nikola.user@bees.mk",
  "password": "supersecret",
  "phone": "070123457",
  "role": "user"
}

### 
GET http://localhost:8080/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoibW9kZXJhdG9yQHRyYWRlLmNvbSIsInJvbGUiOiJtb2RlcmF0b3IiLCJpYXQiOjE3NjM1NDg0ODgsImV4cCI6MTc2MzYzNDg4OH0.-a9W1vYYzzbxfsqz6dzF9nn_7QG_eRe0EcWyItB-vvE


### 
DELETE  http://localhost:8080/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6Im1hcmlqYS5hZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDA5Nzc4NSwiZXhwIjoxNzYwMTg0MTg1fQ.WP8xrJmvjJkoVGcGPxk61oGl_kKkuaRa2bI4lLV67ac
Content-Type: application/json


### Create new product
GET http://localhost:8080/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AdHJhZGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzNTQ5MjcxLCJleHAiOjE3NjM2MzU2NzF9.8DOV1R4uXvi7M4eZiVS2el1K1XXH8ckxsu-K0VqVYEk
Content-Type: application/json

{
  "name": "NestJS нови модули",
  "category": "other",
  "quantity": 10,
  "distributor": "NestJS воведува нови модули за подобра интеграција со микросервиси.",
  "entryDate": "2002-12-12",
  "expirationDate": "2025-12-12",
  "purchasePrice": 50,
  "salePrice": 80,
  "barcode": "121313d"
}



###

GET http://localhost:8080/products/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AdHJhZGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzNTQ5MjcxLCJleHAiOjE3NjM2MzU2NzF9.8DOV1R4uXvi7M4eZiVS2el1K1XXH8ckxsu-K0VqVYEk
Content-Type: application/json


###

PUT http://localhost:8080/products/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AdHJhZGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzNTQ5MjcxLCJleHAiOjE3NjM2MzU2NzF9.8DOV1R4uXvi7M4eZiVS2el1K1XXH8ckxsu-K0VqVYEk
Content-Type: application/json

{
  "quantity": 130,
  "salePrice": 31
}


###
GET http://localhost:8080/products/total-value?mode=purchase
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AdHJhZGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzNTQ5MjcxLCJleHAiOjE3NjM2MzU2NzF9.8DOV1R4uXvi7M4eZiVS2el1K1XXH8ckxsu-K0VqVYEk
Content-Type: application/json



###
GET http://localhost:8080/products/total-value?mode=sale
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AdHJhZGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzNTQ5MjcxLCJleHAiOjE3NjM2MzU2NzF9.8DOV1R4uXvi7M4eZiVS2el1K1XXH8ckxsu-K0VqVYEk
Content-Type: application/json



### 
POST  http://localhost:8080/news/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoibW9kZXJhdG9yQHRyYWRlLmNvbSIsInJvbGUiOiJtb2RlcmF0b3IiLCJpYXQiOjE3NjI4MTUzMjAsImV4cCI6MTc2MjkwMTcyMH0.lHBY7BJ1S5pMNqjvOj1XJu9VxWwhR33B_umIcFFd5J4

{
  "title": "NestJS 2025 Release",
  "content": "New features added in NestJS 2025 version...",
  "author": "Nikola",
  "publishDate": "2025-11-11",
  "category": "technology"
}


### 
GET http://localhost:8080/news?page=1&limit=10
Authorization: Bearer <JWT_TOKEN>


### 
GET http://localhost:8080/news/
Authorization: Bearer <JWT_TOKEN>


### 4️⃣ UPDATE News
PUT http://localhost:8080/news/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AdHJhZGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYzNTQ5MjcxLCJleHAiOjE3NjM2MzU2NzF9.8DOV1R4uXvi7M4eZiVS2el1K1XXH8ckxsu-K0VqVYEk
Content-Type: application/json

{
  "title": "NestJS 2025 Update",
  "category": "technology",
  "content": "Updated content for NestJS 2025 release"
}


### 5️⃣ DELETE News
DELETE http://localhost:8080/news/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE4LCJlbWFpbCI6Im1hcmlqYS5hZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MDEwMTQ3MiwiZXhwIjoxNzYwMTg3ODcyfQ.6XlVLDIhtdcMF95jN-byNlpl-v4RZk4dgVv37EQP-hs

###

### 6️⃣ SEARCH News (Optional)
GET http://localhost:8080/news?search=&page=1&limit=5
Authorization: Bearer <JWT_TOKEN>


### 4️⃣ GET All News with Pagination
GET http://localhost:8080/news?page=1&limit=2
Authorization: Bearer <JWT_TOKEN>


### 5️⃣ SEARCH News by Title
GET http://localhost:8080/news?search=Денес&page=1&limit=5
Authorization: Bearer <JWT_TOKEN>


### 6️⃣ SEARCH News by Category
GET http://localhost:8080/news?search=technology&page=1&limit=10
Authorization: Bearer <JWT_TOKEN>


###
GET http://localhost:8080/forex/fetch